[default]
mission = "test.Stratis"
workshop = [    
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3's Workshop ID
    "3499977893", # Advanced Developer Tools Workshop ID
    "2926014805", # Expanded Assets Browser Workshop ID
]

parameters = [
    "-noPause",
    "-noPauseAudio",
]

[rhs]
extends = "default"
workshop = [
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]

[po]
extends = "rhs"
workshop = [
    "735566597", # Project Opfor Workshop ID
]

[3cbf]
extends = "rhs"
workshop = [
    "1673456286", # 3CB Factions Workshop ID
]

[cup]
extends = "default"
workshop = [
    "497660133", # CUP Weapons
    "541888371", # CUP Vehicles
    "497661914", # CUP Units
]

[cfp]
extends = "cup"
workshop = [
    "1369691841" # CFP
]